In [3]:
import numpy as np

In [ ]:
1. clean the data(outlier,missing values,type conversion)
2. What is the mean value of sepal length
3. sort the sepal width in ascending order.
4. apply all statistical measures on  sepal width and length
5. after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [53]:
iris=np.genfromtxt(r'C:\Users\pavan\Downloads\Iris_clean_-_Copy.csv',dtype='float32',delimiter=',')
iris

array([[      nan,       nan,       nan,       nan],
       [5.100e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.700e+00, 3.200e+00, 1.300e+00, 2.000e-01],
       [4.600e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.400e+00,       nan, 1.700e+00, 4.000e-01],
       [4.600e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.400e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.100e+00,       nan, 1.000e-01],
       [5.400e+00, 3.700e+00, 1.500e+00, 2.000e-01],
       [4.800e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.800e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.300e+00, 3.000e+00, 1.100e+00, 1.000e-01],
       [5.800e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.700e+00, 4.400e+00, 1.500e+00, 4.000e-01],
       [5.040e+01,       nan, 1.300e+00, 4.000e-01],
       [5.100e+00, 3.500e+00, 1.400e+00, 3.000

## SEPAL LENGTH

In [5]:
#sepal length`
sepallength=iris[0:,0]
sepallength

array([  nan,   5.1,   4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,
         4.4,   4.9,   5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,
         5.1,   5.7,   5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,
         5. ,   5.2,   5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,
         5. ,   5.5,   4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,
         5.1,   4.8,   5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,
         5.5,   6.5,   5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,
         6. ,   6.1,   5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,
         6.1,   6.3,   6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,
         5.5,   5.5,   5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,
         5.5,   5.5,   6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,
         5.1,   5.7,   6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,
         7.3,   6.7,   7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,
         6.5,   7.7,   7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,
         7.2,   6.2,

In [6]:
sepallength=np.where(sepallength>=50,2,sepallength)
sepallength

array([nan, 5.1, 4.9, 4.7, 4.6, 2. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8,
       4.8, 4.3, 5.8, 5.7, 2. , 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8,
       5. , 5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9,
       4.4, 5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. ,
       6.4, 6.9, 5.5, 6.5, 5.7, 2. , 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1,
       5.6, 6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8,
       6.7, 6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5,
       5.5, 6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1,
       6.3, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4,
       6.5, 7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4,
       2. , nan, nan, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9,
       5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 5.6, 7.7, nan, nan, 7.2,
       4.9, 7.3, 6.7, 5.9, 5.6, 7.7, 6.3, 7.2, 6.5, 6.4], dtype=float32)

In [7]:
sepallength=np.where(sepallength==-1,np.nan,sepallength)
sepallength

array([nan, 5.1, 4.9, 4.7, 4.6, 2. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8,
       4.8, 4.3, 5.8, 5.7, 2. , 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8,
       5. , 5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9,
       4.4, 5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. ,
       6.4, 6.9, 5.5, 6.5, 5.7, 2. , 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1,
       5.6, 6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8,
       6.7, 6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5,
       5.5, 6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1,
       6.3, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4,
       6.5, 7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4,
       2. , nan, nan, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9,
       5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 5.6, 7.7, nan, nan, 7.2,
       4.9, 7.3, 6.7, 5.9, 5.6, 7.7, 6.3, 7.2, 6.5, 6.4], dtype=float32)

In [8]:
med=np.nanmedian(sepallength)
med

5.8

In [9]:
sepallength=np.where(np.isnan(sepallength),med,sepallength)
sepallength

array([5.8, 5.1, 4.9, 4.7, 4.6, 2. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8,
       4.8, 4.3, 5.8, 5.7, 2. , 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8,
       5. , 5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9,
       4.4, 5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. ,
       6.4, 6.9, 5.5, 6.5, 5.7, 2. , 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1,
       5.6, 6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8,
       6.7, 6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5,
       5.5, 6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1,
       6.3, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4,
       6.5, 7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4,
       2. , 5.8, 5.8, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9,
       5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 5.6, 7.7, 5.8, 5.8, 7.2,
       4.9, 7.3, 6.7, 5.9, 5.6, 7.7, 6.3, 7.2, 6.5, 6.4], dtype=float32)

In [10]:
sepallengthd=sepallength.dtype="float32"
sepallengthd

'float32'

In [11]:
sepallength.dtype

dtype('float32')

## SEPAL WIDTH

In [12]:
sepalwidth=iris[1:,1]
sepalwidth

array([  3.5,   3. ,   3.2,   3.1,   3.6,   nan,   3.4,   3.4,   2.9,
         3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   nan,   3.5,
         3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,
         3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,
         3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,
         3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   nan,   2.3,
         2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,
         2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,
         2.5,   nan,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,
         2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,
         2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,
         2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,
         2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,
         3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,
         2.8,   3. ,

In [13]:
sepalwidth=np.where(sepalwidth>=30,5,sepalwidth)
sepalwidth

array([3.5, 3. , 3.2, 3.1, 3.6, nan, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 5. ,
       3. , 4. , 4.4, nan, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       5. , 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       nan, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, nan, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 5. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, nan, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, nan, 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3.6, 3.2, 2.7], dtype=float32)

In [14]:
sepalwidth=np.where(sepalwidth==-1,np.nan,sepalwidth)
sepalwidth

array([3.5, 3. , 3.2, 3.1, 3.6, nan, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 5. ,
       3. , 4. , 4.4, nan, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       5. , 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       nan, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, nan, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 5. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, nan, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, nan, 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3.6, 3.2, 2.7], dtype=float32)

In [15]:
med1=np.nanmedian(sepalwidth)
med1

3.0

In [16]:
sepalwidth=np.where(np.isnan(sepalwidth),med1,sepalwidth)
sepalwidth

array([3.5, 3. , 3.2, 3.1, 3.6, 3. , 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 5. ,
       3. , 4. , 4.4, 3. , 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       5. , 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3. , 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 3. , 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 5. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3. , 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3.6, 3.2, 2.7], dtype=float32)

In [17]:
sepalwidth.dtype

dtype('float32')

In [132]:
sepalwidth.dtype="float32"

In [18]:
sepalwidth.dtype

dtype('float32')

## petal length

In [19]:
petallength=iris[2:,2]
petallength

array([ 1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  nan,  1.5,  1.6,
        1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,  1. ,
        1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,  1.4,
        1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,  1.6,  1.9,
        1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,  4.5,
        4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,  4.5,
        4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,  5. ,
        4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,  4.1,
        4. ,  4.4,  nan,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,  4.1,
        6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,  5.1,
        5.3,  nan,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,  4.9,
        6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  nan,  5.6,
        5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  nan,  5.1,  5.1,  5.9,
        5.7,  nan,  5. ,  5.2,  5.4,  5.1,  4.9,  6

In [20]:
petallength=np.where(petallength>=7,np.nan,petallength)
petallength

array([1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, nan, 1.5, 1.6, 1.4, 1.1,
       1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6, 1.6,
       1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3, 1.5,
       1.3, nan, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5, 4.9,
       4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6, 4.4,
       4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. , 4.5,
       3.5, nan, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4, nan,
       4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6, 5.8,
       6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, nan, 5. , 5.1, 5.3, 5.5, 6.7,
       6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8, 6.1,
       nan, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, nan, 5.1, 5.1, 5.9,
       5.7, nan, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. , 4.5, 6.3,
       5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3], dtype=float32)

In [21]:
med2=np.nanmedian(petallength)
med2

4.5

In [22]:
petallength=np.where(np.isnan(petallength),med2,petallength)
petallength

array([1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 4.5, 1.5, 1.6, 1.4, 1.1,
       1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6, 1.6,
       1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3, 1.5,
       1.3, 4.5, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5, 4.9,
       4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6, 4.4,
       4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. , 4.5,
       3.5, 4.5, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4, 4.5,
       4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6, 5.8,
       6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 4.5, 5. , 5.1, 5.3, 5.5, 6.7,
       6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8, 6.1,
       4.5, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 4.5, 5.1, 5.1, 5.9,
       5.7, 4.5, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. , 4.5, 6.3,
       5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3], dtype=float32)

In [23]:
petallength.dtype

dtype('float32')

In [24]:
petallength.dtype="float64"

In [25]:
petallength.dtype

dtype('float64')

## petalwidth

In [26]:
petalwidth=iris[3:,3]
petalwidth

array([2.000e-01, 1.020e+01, 2.000e-01, 4.000e-01, 3.000e-01, 2.000e-01,
       2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01, 1.010e+01, 1.000e-01,
       2.000e-01, 4.000e-01, 4.000e-01, 3.000e-01, 3.000e-01, 3.000e-01,
       2.000e-01, 4.000e-01, 2.000e-01, 5.000e-01, 2.000e-01, 2.000e-01,
       4.000e-01, 2.000e-01, 1.102e+02, 2.000e-01, 2.000e-01, 4.000e-01,
       1.000e-01, 2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01, 1.000e-01,
       2.000e-01, 2.000e-01, 3.000e-01, 3.000e-01, 2.000e-01, 6.000e-01,
       4.000e-01, 3.000e-01, 2.000e-01, 2.000e-01, 2.000e-01, 2.000e-01,
       1.400e+00, 1.500e+00, 1.500e+00, 1.300e+00, 1.500e+00, 1.300e+00,
       1.600e+00, 1.600e+01, 1.300e+00, 1.400e+00, 1.000e+00, 1.500e+00,
       1.000e+00, 1.400e+00, 1.300e+00, 1.400e+00, 1.500e+00, 1.000e+00,
       1.500e+00, 1.100e+00, 1.800e+00, 1.300e+00, 1.500e+00, 1.200e+00,
       1.300e+00, 1.400e+00, 1.400e+00, 1.700e+00, 1.500e+00, 1.000e+00,
       1.100e+00, 1.000e+00, 1.200e+00, 1.600e+00, 

In [27]:
petalwidth=np.where(petalwidth>=10,1.5,petalwidth)
petalwidth

array([0.2, 1.5, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 1.5, 0.1, 0.2,
       0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2, 0.4, 0.2,
       1.5, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2, 0.2, 0.3,
       0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5, 1.5, 1.3,
       1.5, 1.3, 1.6, 1.5, 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3, 1.4, 1.5,
       1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7, 1.5, 1. ,
       1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2, 1.4, 1.2,
       1. , 1.3, 1.2, 1.3, 1.3, 1.5, 1.3, 2.5, 1.9, 2.1, 1.8, 2.2, 2.1,
       1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8, 2.2, 2.3,
       1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6, 1.9, 2. ,
       2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9, 2.3, 2.5,
       2.3, 1.9, 2. , 2.3, 1.8, 2. , 2. , 1.8, 2.1, 1.8, 1.7, 1.8, 1.8,
       1.8, 2. , 2. , 1.8, 2.5, 2. , 1.9], dtype=float32)

## What is the mean value of sepal length

In [28]:
sepallength.dtype="float32"

In [29]:
sepallength.mean()

5.778916

 ## sort the sepal width in ascending order.

In [30]:
np.sort(sepalwidth)

array([2. , 2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.5, 2.5,
       2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.6, 2.6, 2.6, 2.6, 2.7,
       2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.8, 2.8,
       2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8,
       2.8, 2.8, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1,
       3.1, 3.1, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2,
       3.2, 3.2, 3.2, 3.2, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.4, 3.4,
       3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.5, 3.5, 3.5, 3.5,
       3.5, 3.5, 3.6, 3.6, 3.6, 3.6, 3.7, 3.7, 3.7, 3.8, 3.8, 3.8, 3.8,
       3.8, 3.8, 4. , 4.1, 4.2, 4.4, 5. , 5. , 5. ], dtype=float32)

## apply all statistical measures on  sepal width and length

## sepalwidth

In [31]:
sepalwidth.mean()

3.0654545

In [32]:
np.median(sepalwidth)

3.0

In [33]:
sepalwidth.min()

2.0

In [34]:
sepalwidth.max()

5.0

In [35]:
range1=sepalwidth.max()-sepalwidth.min()
range1

3.0

In [36]:
#variance
np.var(sepalwidth)

0.23765509

In [37]:
#standard deviation
np.std(sepalwidth)

0.48749882

## sepallength

In [38]:
sepallength.mean()

5.778916

In [39]:
np.median(sepallength)

5.8

In [40]:
sepallength.max()

7.7

In [41]:
sepalwidth.min()

2.0

In [42]:
range2=sepalwidth.max()-sepalwidth.min()
range2

3.0

In [43]:
#variance
np.var(sepalwidth)

0.23765509

In [44]:
#standard deviation
np.std(sepalwidth)

0.48749882

In [45]:
com=np.hstack((sepallength,sepalwidth))
com

array([5.8, 5.1, 4.9, 4.7, 4.6, 2. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8,
       4.8, 4.3, 5.8, 5.7, 2. , 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8,
       5. , 5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9,
       4.4, 5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. ,
       6.4, 6.9, 5.5, 6.5, 5.7, 2. , 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1,
       5.6, 6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8,
       6.7, 6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5,
       5.5, 6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1,
       6.3, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4,
       6.5, 7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4,
       2. , 5.8, 5.8, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9,
       5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 5.6, 7.7, 5.8, 5.8, 7.2,
       4.9, 7.3, 6.7, 5.9, 5.6, 7.7, 6.3, 7.2, 6.5, 6.4, 3.5, 3. , 3.2,
       3.1, 3.6, 3. , 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 5. , 3. , 4.

In [50]:
two=np.hstack((petallength,petalwidth))
two

array([4.37499955e-02, 7.50000029e-02, 7.50000029e-02, 7.50000029e-02,
       1.25000030e-01, 7.50000029e-02, 2.50000097e-02, 4.37499955e-02,
       4.00000155e-01, 4.00000155e-01, 7.81250186e-03, 1.20000005e+00,
       2.25000054e-01, 7.50000029e-02, 2.25000054e-01, 1.25000030e-01,
       1.25000030e-01, 4.37499955e-02, 4.37499955e-02, 4.37499955e-02,
       4.37499956e-02, 1.20000005e+00, 2.25000054e-01, 1.25000030e-01,
       1.43359985e+03, 1.84320044e+03, 1.22880005e+03, 1.43359986e+03,
       1.22880005e+03, 1.28000031e+02, 5.12000123e+02, 1.79199982e+02,
       1.02400025e+03, 1.02400025e+03, 1.63840064e+03, 1.84320044e+03,
       8.19200319e+02, 1.63840064e+03, 1.02400025e+03, 1.02400025e+03,
       4.09600159e+02, 1.02400025e+03, 1.43359986e+03, 6.14400025e+02,
       9.21600221e+02, 5.12000123e+02, 7.16799927e+02, 7.16799928e+02,
       3.20000077e+01, 8.19200197e+03, 7.37280177e+03, 6.55360255e+03,
       1.02400025e+03, 6.55360255e+03, 2.45760010e+03, 1.02400025e+03,
      

In [47]:
iris_flower=np.hstack((com,two))

In [48]:
np.savetxt('cleaned_iris.txt',iris_flower)

In [49]:
np.loadtxt('cleaned_iris.txt')

array([5.80000019e+00, 5.09999990e+00, 4.90000010e+00, 4.69999981e+00,
       4.59999990e+00, 2.00000000e+00, 5.40000010e+00, 4.59999990e+00,
       5.00000000e+00, 4.40000010e+00, 4.90000010e+00, 5.40000010e+00,
       4.80000019e+00, 4.80000019e+00, 4.30000019e+00, 5.80000019e+00,
       5.69999981e+00, 2.00000000e+00, 5.09999990e+00, 5.69999981e+00,
       5.09999990e+00, 5.40000010e+00, 5.09999990e+00, 4.59999990e+00,
       5.09999990e+00, 4.80000019e+00, 5.00000000e+00, 5.00000000e+00,
       5.19999981e+00, 5.19999981e+00, 4.69999981e+00, 4.80000019e+00,
       5.40000010e+00, 5.19999981e+00, 5.50000000e+00, 4.90000010e+00,
       5.00000000e+00, 5.50000000e+00, 4.90000010e+00, 4.40000010e+00,
       5.09999990e+00, 5.00000000e+00, 4.50000000e+00, 4.40000010e+00,
       5.00000000e+00, 5.09999990e+00, 4.80000019e+00, 5.09999990e+00,
       4.59999990e+00, 5.30000019e+00, 5.00000000e+00, 7.00000000e+00,
       6.40000010e+00, 6.90000010e+00, 5.50000000e+00, 6.50000000e+00,
      