
## Creation of ndarray

* 1.Write python code to create 3d array in different ways with 15 elements.
* 2.Array Creation:
* a. Create a 4D NumPy array containing the first 12 positive integers as arr1. b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1. 3. Find all attributes of array1 and array2 4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

## Array Slicing and Indexing:

a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. - Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].

b.Basic Indexing: - Print the element at index 3 of arr1. - Print the element at row 2, column 1 of arr2

c. Array Slicing: - Print the first five elements of arr1. - Print the subarray of arr2 consisting of the last two rows and the first two columns. - Print every second element starting from index 1 up to index 7 of arr1.

Data Type Manipulation

a. Creating Arrays with Specific Data Types: - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. - Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.

b. Data Type Conversion: - Convert the float_array to an array with data type int32. Print the result. - Convert the int_array to an array with data type float32. Print the result.

## Generating Random Numbers:

1.Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2.Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3.Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4.Apply descriptive statistics for rand_matrix.

## Analyze the Data:

#### Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

1.Describe the data using numpy array. Measure the following:

2.How many employees are getting more less than 50000?

3.Is it following Normal Distribution?

4.What is the median salary?

5.What is the range of salaries for this company?

6.Find the salaries between average salary and 75% of salaries?

7.How many employees are getting less than 25 % of salaries ?

 

In [2]:
import numpy as np 

## 1.Write python code to create 3d array in different ways with 15 elements.

In [6]:
array=np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]])
array

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [7]:
array.ndim

3

In [8]:
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],ndmin=3)
array

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [9]:
array.ndim

3

In [18]:
array=[np.arange(0,15).reshape(3,1,5)]
array

[array([[[ 0,  1,  2,  3,  4]],
 
        [[ 5,  6,  7,  8,  9]],
 
        [[10, 11, 12, 13, 14]]])]

## 2.Array Creation:
* a. Create a 4D NumPy array containing the first 12 positive integers as arr1. 
* b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.
* c. Find all attributes of array1 and array2 
* d. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

In [35]:
arr1=np.arange(1,13).reshape(3,2,1,2)
array1=np.random.randint(0,1,20).reshape(2,2,5)

In [36]:
arr1

array([[[[ 1,  2]],

        [[ 3,  4]]],


       [[[ 5,  6]],

        [[ 7,  8]]],


       [[[ 9, 10]],

        [[11, 12]]]])

In [37]:
array1

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

## attributes

In [38]:
arr1.dtype

dtype('int32')

In [39]:
arr1.ndim

4

In [40]:
arr1.max()

12

In [41]:
arr1.min()

1

In [42]:
arr1.size

12

In [43]:
arr1.itemsize

4

In [44]:
arr1.nbytes

48

In [45]:
array1.dtype

dtype('int32')

In [46]:
array1.ndim

3

In [47]:
array1.max()

0

In [48]:
array1.min()

0

In [49]:
array1.size

20

In [50]:
array1.itemsize

4

In [51]:
array1.nbytes

80

## statistical measures

### measure of central tendency

## arr1

In [52]:
arr1.mean()

6.5

In [54]:
np.median(arr1)

6.5

In [56]:
np.max(arr1)

12

In [57]:
np.min(arr1)

1

## array1

In [58]:
array1.mean()

0.0

In [60]:
np.median(array1)

0.0

In [61]:
np.max(array1)

0

In [62]:
np.min(array1)

0

## measure of dispersion

## arr1

In [65]:
#range
range1=np.max(arr1)-np.min(arr1)
range1

11

In [67]:
#variance
np.var(arr1)

11.916666666666666

In [68]:
#standard deviation
np.std(arr1)

3.452052529534663

## arr1--IQR

In [69]:
q1=np.percentile(arr1,25)
q1

3.75

In [70]:
q2=np.percentile(arr1,50)
q2

6.5

In [72]:
q3=np.percentile(arr1,75)
q3

9.25

In [73]:
iqr=q3-q1
iqr

5.5

In [75]:
lower=q1-(1.5*iqr)
lower

-4.5

In [76]:
upper=q3+(1.5*iqr)
upper

17.5

In [77]:
arr1[arr1>upper]

array([], dtype=int32)

In [78]:
arr1[arr1<lower]

array([], dtype=int32)

## array1

In [83]:
#range
range2=np.max(array1)-np.min(array1)
range2

0

In [84]:
#variance
np.var(array1)

0.0

In [85]:
#standard deviation
np.std(array1)

0.0

## array1--IQR

In [87]:
q1=np.percentile(array1,25)
q1

0.0

In [88]:
q2=np.percentile(array1,50)
q2

0.0

In [89]:
q3=np.percentile(array1,75)
q3

0.0

In [90]:
iqr=q3-q1
iqr

0.0

In [91]:
lower=q1-(1.5*iqr)
upper=q3+(1.5*iqr)

In [92]:
array1[array1>upper]

array([], dtype=int32)

In [93]:
array1[array1<lower]

array([], dtype=int32)

Array Slicing and Indexing:
a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. - Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].

b.Basic Indexing: - Print the element at index 3 of arr1. - Print the element at row 2, column 1 of arr2

c. Array Slicing: - Print the first five elements of arr1. - Print the subarray of arr2 consisting of the last two rows and the first two columns. - Print every second element starting from index 1 up to index 7 of arr1.

Data Type Manipulation

a. Creating Arrays with Specific Data Types: - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. - Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.

b. Data Type Conversion: - Convert the float_array to an array with data type int32. Print the result. - Convert the int_array to an array with data type float32. Print the result.

In [3]:
arr1=np.array([0,11,26,73,42,51,6,77,8,29])
arr2=np.array( [[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [4]:
arr1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

In [5]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## indexing

In [6]:
arr1[3]

73

In [7]:
arr2[2,1]

7

## slicing

In [8]:
arr1[:5]

array([ 0, 11, 26, 73, 42])

In [13]:
arr2[1:,0:2]

array([[3, 4],
       [6, 7]])

In [15]:
arr1[1:8:2]

array([11, 73, 51, 77])

## data manipulation

In [16]:
int_array=np.array([1, 2, 3, 4, 5],dtype='int16')

In [19]:
int_array.dtype

dtype('int16')

In [20]:
float_array=np.array( [0.1, 0.2, 0.3, 0.4, 0.5],dtype='float64')

In [21]:
float_array.dtype

dtype('float64')

In [22]:
fint_array=np.array([1, 2, 3, 4, 5],dtype="float32")

In [23]:
fint_array.dtype

dtype('float32')

In [24]:
ifloat_array=np.array( [0.1, 0.2, 0.3, 0.4, 0.5],dtype='int32')

In [25]:
ifloat_array.dtype

dtype('int32')

## Generating Random Numbers:

1.Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2.Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3.Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4.Apply descriptive statistics for rand_matrix.

In [26]:
ran_array=np.random.randint(0,101,10)
ran_array

array([45, 73, 99, 18, 50, 55, 79, 64, 67, 79])

In [27]:
u_array=np.random.uniform(-1,1,5)
u_array

array([-0.92649074, -0.27967867,  0.41136571,  0.33502364,  0.84908901])

In [36]:
rand_matrix=np.random.randint(50,101,12).reshape(3,4)
rand_matrix

array([[73, 79, 92, 56],
       [60, 65, 59, 91],
       [97, 91, 92, 65]])

## Descriptive statistics

In [37]:
rand_matrix.mean()

76.66666666666667

In [38]:
np.median(rand_matrix)

76.0

In [40]:
rand_matrix.max()

97

In [42]:
rand_matrix.min()

56

In [43]:
range1=rand_matrix.max()-rand_matrix.min()
range1

41

In [44]:
rand_matrix.var()

216.88888888888889

In [45]:
rand_matrix.std()

14.727148022916348

## IQR

In [46]:
q1=np.percentile(rand_matrix,25)
q1

63.75

In [47]:
q2=np.percentile(rand_matrix,50)
q2

76.0

In [48]:
q3=np.percentile(rand_matrix,75)
q3

91.25

In [49]:
iqr=q3-q1
iqr

27.5

In [50]:
lower=q1-(1.5*iqr)
upper=q3+(1.5*iqr)

In [51]:
rand_matrix[rand_matrix>upper]

array([], dtype=int32)

In [52]:
rand_matrix[rand_matrix<lower]

array([], dtype=int32)

## Analyze the Data:
#### Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

1.Describe the data using numpy array. Measure the following:

2.How many employees are getting more less than 50000?

3.Is it following Normal Distribution?

4.What is the median salary?

5.What is the range of salaries for this company?

6.Find the salaries between average salary and 75% of salaries?

7.How many employees are getting less than 25 % of salaries ?

In [54]:
salaries=np.array( [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638])

In [55]:
salaries[salaries<50000]

array([31250, 39828, 41671, 34225, 32199])

In [56]:
len(salaries[salaries<50000])

5

In [57]:
# median
np.median(salaries)

61699.5

In [61]:
salaries.min()
salaries.max()
range2=salaries.max()-salaries.min()
range2

3082388

In [64]:
avg=salaries.mean()
avg

166169.16666666666

In [65]:
q1=np.percentile(salaries,25)
q1

52963.25

In [66]:
q3=np.percentile(salaries,75)
q3

84496.5

In [81]:
salaries[(salaries > avg)]

array([3113638])

In [82]:
salaries[(salaries<q3)]

array([54494, 54804, 52453, 31250, 66349, 39828, 60501, 58570, 74906,
       41671, 51428, 56414, 56819, 82833, 50477, 62898, 34225, 79172,
       32199, 63795, 55723, 64557])

In [83]:
salaries[(salaries<q1)]

array([52453, 31250, 39828, 41671, 51428, 50477, 34225, 32199])

In [84]:
len(salaries[(salaries<q1)])

8