## Data Cleaning using numpy

### The following are the student marks of a class [44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]


* 1.Find the no of outliers and missing values?
* 2.replace the outliers with 45 and missing value with 87.
* 3.what is the average marks of students after 2nd step?
* 4.How many students got less than 60 marks?
* 5.what is the maximum marks?
* 6.Convert the marks to float32.

## Solving Linear Equations

1. 2x + 3y - z = 10

   x - y + 2z = 5

   3x + 2y + z = 12


2. 2x + y - z + 3w = 8

   3x - 2y + 2z + 2w = 1

   x + 3y - 2z + w = 7

   4x - y + z - 2w = 3


3. 4x + 2y - 3z = 10

   -2x + 3y + z = -3

    x - y + 2z = 4

Solve the system of equations using NumPy's linalg.solve function.

## Conditional Selection with np.where()

1.Generate a random 1D array A of 10 integers between 1 and 100.

2.Use np.where() to find the indices where the elements of A are greater than 50.

3.Create a new array B that contains elements from A where the condition is met.

4.Calculate the mean of array B and print it along with arrays A and B.

## Replace Values with np.where()

1.Create a 4x4 random integer matrix C with values between -10 and 10.

2.Use np.where() to replace all negative values in matrix C with 0.

3.Print the original matrix C and the modified matrix.

 

In [7]:
import numpy as np


## Data Cleaning using numpy

In [17]:
marks=np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53, 44])
marks

array([ 44.,  24.,  nan,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  nan,  nan,   3.,  56.,  81.,  59., 122.,  92.,  nan,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

In [11]:
np.isnan(marks)

array([False, False,  True, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False])

In [24]:
marks=np.where(np.isnan(marks),45,marks)
marks

array([ 44.,  24.,  45.,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  45.,  45.,   3.,  56.,  81.,  59., 122.,  92.,  45.,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.], dtype=float32)

In [25]:
marks.dtype

dtype('float32')

In [26]:
average=marks.mean()
average

61.344826

In [27]:
marks[marks<60]

array([44., 24., 45., 59., 32., 52., 58., 52., 45., 45.,  3., 56., 59.,
       45.,  1., 19.,  2., 53., 44.], dtype=float32)

In [28]:
len(marks[marks<60])

19

In [29]:
marks.max()

188.0

In [32]:
marks=np.array(marks).astype('float32')

In [33]:
marks.dtype

dtype('float32')

## Solving Linear Equations


In [ ]:
1.2x + 3y - z = 10

  x - y + 2z = 5

  3x + 2y + z = 12

2.2x + y - z + 3w = 8

  3x - 2y + 2z + 2w = 1

  x + 3y - 2z + w = 7

  4x - y + z - 2w = 3

3.4x + 2y - 3z = 10

  -2x + 3y + z = -3

  x - y + 2z = 4

In [34]:
#1
a=np.array([[2,3,-1],[1,-1,2],[3,2,1]])
b=np.array([10,5,12])

In [35]:
np.linalg.solve(a,b)

array([-6.75539944e+15,  6.75539944e+15,  6.75539944e+15])

In [36]:
#2
a=np.array([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])
b=np.array([8,1,7,3])

In [37]:
np.linalg.solve(a,b)

array([ 1.73170732, -0.75609756, -3.46341463,  0.6097561 ])

In [38]:
#3
a=np.array([[4,2,-3],[-2,3,1],[1,-1,2]])
b=np.array([10,-3,4])

In [39]:
np.linalg.solve(a,b)

array([2.85365854, 0.6097561 , 0.87804878])

## Conditional Selection with np.where()

In [52]:
A=np.random.randint(1,101,10)

In [53]:
A

array([35, 75, 83, 34, 65, 33, 81,  7, 14, 40])

In [55]:
a=np.array([35, 75, 83, 34, 65, 33, 81,  7, 14, 40])
a

array([35, 75, 83, 34, 65, 33, 81,  7, 14, 40])

In [56]:
indices=a[a>50]
indices

array([75, 83, 65, 81])

In [57]:
b=[indices]
b

[array([75, 83, 65, 81])]

In [59]:
B=np.mean(b)
B

76.0

In [60]:
a

array([35, 75, 83, 34, 65, 33, 81,  7, 14, 40])

In [61]:
b

[array([75, 83, 65, 81])]

In [62]:
B

76.0

## Replace Values with np.where()

In [72]:
matc=np.random.randint(-10,10,size=(4,4))
matc

array([[ 3, -6, -2,  1],
       [ 9, -9,  5,  8],
       [ 4,  4,  4,  0],
       [-2,  4, -4,  6]])

In [78]:
c=np.array([[ 3, -6, -2,  1],
       [ 9, -9,  5,  8],
       [ 4,  4,  4,  0],
       [-2,  4, -4,  6]],ndmin=4)
c

array([[[[ 3, -6, -2,  1],
         [ 9, -9,  5,  8],
         [ 4,  4,  4,  0],
         [-2,  4, -4,  6]]]])

In [80]:
c.ndim

4

In [81]:
c=np.where(c<0,0,c)
c

array([[[[3, 0, 0, 1],
         [9, 0, 5, 8],
         [4, 4, 4, 0],
         [0, 4, 0, 6]]]])